import subprocess,json,pathlib,hashlib,stat,datetime
names=['insignia-rewrite-m5-019-web','insignia-rewrite-m5-019-database','insignia-app','traefik'];cs=json.loads(subprocess.check_output(['docker','inspect']+names,text=True));c=cs[0];labels=c['Config']['Labels'];hc=c['HostConfig']
assert c['Config']['User']=='node' and hc['ReadonlyRootfs'] and hc['CapDrop']==['ALL'] and 'no-new-privileges:true' in hc['SecurityOpt']
assert c['Id']=='c81927922a3b9b3b7f37e305e4f1bc6dde730c3b42cbcd5af457415b01230621' and c['State']['Health']['Status']=='healthy'
assert 'APP_URL=https://insignia-app.optidigi.nl' in c['Config']['Env'] and labels['traefik.enable']=='true'
assert labels['traefik.http.routers.insignia-canonical-m5-019r.rule']=='Host(`insignia-app.optidigi.nl`)'
assert c['Image']=='sha256:8aa439cb733160ce6b99165e8401cfbc60f612851aeef0d76735db92917dc3f5' and all(v is None for v in c['NetworkSettings']['Ports'].values())
p=pathlib.Path('/home/serveradmin/insignia-rewrite-m5-019');modes={n:oct(stat.S_IMODE((p/n).stat().st_mode)) for n in ['.env','runtime.env','database.env']};assert set(modes.values())=={'0o600'}
entry=subprocess.check_output(['docker','exec',names[0],'sha256sum','dist/server/entry.mjs'],text=True).split()[0];assert entry=='5dab1e4f21a7033582c1c2a326c97d6dcadae66ca04566a73a2aca113b4077f7'
print(json.dumps({'observedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'classification':'CANONICAL_FINAL_OWNERSHIP_ARTIFACT_AND_HARDENING_PASS','runtimeAppUrl':'https://insignia-app.optidigi.nl','clientId':'1443cf6d03d39edae7c101a943c5c684','webImage':c['Image'],'webEntrySha256':entry,'packageSha256':hashlib.sha256((p/'reviewed-web-package.tar.gz').read_bytes()).hexdigest(),'composeSha256':hashlib.sha256((p/'compose.yaml').read_bytes()).hexdigest(),'nonRootUser':c['Config']['User'],'readOnlyRootFs':hc['ReadonlyRootfs'],'allCapabilitiesDropped':True,'noNewPrivileges':True,'noPublishedWebOrDatabasePorts':all(v is None for x in cs[:2] for v in x['NetworkSettings']['Ports'].values()),'privateFileModesOnly':modes,'canonicalHostRule':labels['traefik.http.routers.insignia-canonical-m5-019r.rule'],'containers':[{'name':x['Name'],'id':x['Id'],'image':x['Image'],'startedAt':x['State']['StartedAt'],'status':x['State']['Status'],'health':x['State'].get('Health',{}).get('Status')} for x in cs],'noBuildOrMigrations':True,'shopifyVersionCreates':0,'releases':0},indent=2))
