# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "942e6668fd1177524c0fc48b104b0ac3"
application_url = "https://example.com"
embedded = true
name = "insignia"
web_directories = ["web"]

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_cart_transforms,write_cart_transforms,write_products,write_inventory,read_locations"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[build]
automatically_update_urls_on_dev = true
