[package]
name = "m0-006-cart-validation"
version = "0.1.0"
edition = "2021"

[dependencies]
insignia-m0-005-authorization = { path = "../../../m0-005/rust/authorization" }
shopify_function = "=2.2.0"

[dev-dependencies]
serde_json = "=1.0.151"

[profile.release]
lto = true
opt-level = 3
strip = true
