api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "m0-001-same-variant"
type = "function"
uid = "aa01e1a8-3968-9594-a281-afc819fd748570a2a786"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/m0-001-same-variant.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
