query Input {
  buyerJourney { step }
  cart {
    lines {
      id
      quantity
      auth: attribute(key: "_insignia_auth") { value }
      cost {
        amountPerQuantity { currencyCode }
        subtotalAmount { amount currencyCode }
      }
      sellingPlanAllocation { sellingPlan { id } }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product { policy: metafield(key: "m0_004_policy") { value } }
        }
      }
    }
  }
  localization { country { isoCode } market { id } }
  shop {
    localTime { date }
    publicConfig: metafield(key: "m0_004_public_config") { value }
  }
}
